name: Unit Testing CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      ACTIONS_UNIT_TESTS: "1"
    steps:

      - name: Apt Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev pkg-config libwayland-dev libxkbcommon-dev xorg-dev


      - name: Setup sccache Variables
        run: |
          echo "SCCACHE_ENDPOINT=https://0b13f25b65dea5d733abbbaa9b689381.r2.cloudflarestorage.com" >> $GITHUB_ENV
          echo "SCCACHE_BUCKET=sccache" >> $GITHUB_ENV
          echo "SCCACHE_REGION=auto" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV 
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - uses: mozilla-actions/sccache-action@v0.0.6
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: jwlawson/actions-setup-cmake@v2

      - name: CMake Configure
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: >
          cmake -Bbuild -GNinja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          -DWEBGPU_BACKEND=DAWN

      - name: CMake Build Tests
        run: cmake --build build -t tests

      - name: Run Tests
        run: build/tests/tests

