name: Unit Testing CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake Configure
        run: >
          cmake -Bbuild -GNinja
          -DCMAKE_BUILD_TYPE=Debug

      - name: CMake Build Tests
        run: cmake --build build -t tests

      - name: Run Tests
        run: build/tests/tests

